import type { StoreChangeMetrics, ReportSummary } from "@/app/(dashboard)/reports/page";

export const exportToCSV = (
  changes: StoreChangeMetrics[],
  summary: ReportSummary,
  filename?: string
) => {
  const headers = [
    "Store ID", "Store Name", "Province", "Change Type", "Success Score", 
    "Revenue Impact", "Sell Through Rate", "Waste Reduction", 
    "Operational Efficiency", "Previous Status", "Current Status", "Change Date", "Notes"
  ];
  
  const csvData = changes.map(change => [
    change.storeId,
    change.storeName,
    change.province,
    change.changeType.replace(/_/g, ' ').toUpperCase(),
    change.successScore,
    change.revenueImpact || 0,
    `${change.performanceMetrics.sellThroughRate}%`,
    `${change.performanceMetrics.wasteReduction}%`,
    `${change.performanceMetrics.operationalEfficiency}%`,
    change.previousStatus,
    change.currentStatus,
    change.changeDate.toISOString().split('T')[0],
    change.notes || ""
  ]);

  const csvContent = [headers, ...csvData]
    .map(row => row.map(cell => `"${cell}"`).join(','))
    .join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `stillgood-store-changes-report-${new Date().toISOString().split('T')[0]}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const exportSummaryToJSON = (summary: ReportSummary, filename?: string) => {
  const jsonContent = JSON.stringify(summary, null, 2);
  const blob = new Blob([jsonContent], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `stillgood-summary-report-${new Date().toISOString().split('T')[0]}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const generateExecutiveSummaryText = (summary: ReportSummary, changes: StoreChangeMetrics[]): string => {
  const completionRate = Math.round((summary.completedRollouts / summary.totalStores) * 100);
  const topPerformingProvince = Object.entries(summary.provinceBreakdown)
    .sort(([,a], [,b]) => b - a)[0];
  
  const recentImprovements = changes.filter(c => c.successScore >= 80).length;
  const concerningChanges = changes.filter(c => c.successScore < 50).length;
  
  return `
STILLGOOD CRM - EXECUTIVE SUMMARY
Generated: ${new Date().toLocaleDateString()}

OVERVIEW
--------
Total Stores: ${summary.totalStores}
Active Stores: ${summary.activeStores}
Completed Rollouts: ${summary.completedRollouts} (${completionRate}%)
Average Success Score: ${summary.averageSuccessScore}%

FINANCIAL IMPACT
---------------
Total Revenue (Period): R${summary.totalRevenue.toLocaleString()}
Training Sessions Completed: ${summary.trainingSessions}

PERFORMANCE ANALYSIS
-------------------
High-Performing Changes (80%+ success): ${recentImprovements}
Concerning Changes (<50% success): ${concerningChanges}
Top Performing Province: ${topPerformingProvince ? topPerformingProvince[0] : 'N/A'} (${topPerformingProvince ? topPerformingProvince[1] : 0} stores)

MONTHLY TRENDS
--------------
${summary.monthlyTrends.map(trend => 
  `${trend.month}: ${trend.completions} completions, R${trend.revenue.toLocaleString()} revenue, ${trend.successRate}% success rate`
).join('\n')}

RECOMMENDATIONS
--------------
${completionRate < 50 ? '• Focus on accelerating rollout completion to reach 50%+ completion rate\n' : ''}${summary.averageSuccessScore < 70 ? '• Investigate and address factors causing low success scores\n' : ''}${concerningChanges > 0 ? '• Review and provide additional support to underperforming stores\n' : ''}• Continue monitoring and supporting high-performing stores
• Consider replicating successful strategies from top-performing provinces

Report prepared for: james@stillgood.co.za
Generated by: StillGood CRM Reports Dashboard
  `.trim();
};